const scanStatus=t=>$('scan-status').textContent=t;
let rotation={x:-15,y:15};let dragging=false,last={x:0,y:0};
function orient(){ $('universe').style.transform=`rotateX(${rotation.x}deg) rotateY(${rotation.y}deg)`; }
const view=$('viewport');view.onpointerdown=e=>{dragging=true;last={x:e.clientX,y:e.clientY};view.setPointerCapture(e.pointerId);};view.onpointerup=()=>dragging=false;view.onpointercancel=()=>dragging=false;view.onpointermove=e=>{if(!dragging)return;rotation.y+=(e.clientX-last.x)*.5;rotation.x-=(e.clientY-last.y)*.5;last={x:e.clientX,y:e.clientY};orient();};
$('reset-view').onclick=()=>{rotation={x:-15,y:15};orient();};
// Future hardware adapters supply degrees after pairing/authentication. No Bluetooth connection is claimed here.
window.jarvisOrientation=({pitch,roll})=>{if(!Number.isFinite(pitch)||!Number.isFinite(roll))return;rotation.x=Math.max(-80,Math.min(80,pitch));rotation.y=roll%360;orient();};
function draw(hosts,target){const world=$('universe');world.replaceChildren();$('results').replaceChildren();const center=document.createElement('div');center.className='node host';center.textContent=target||'IP를 입력하세요';world.append(center);const ports=hosts.flatMap(h=>h.ports);ports.forEach((p,i)=>{const angle=i*Math.PI*2/Math.max(1,ports.length);const ring=Math.floor(i/16);const node=document.createElement('div');node.className='node'+(p.state==='open'?'':' other');node.style.transform=`translate3d(${Math.cos(angle)*(170+ring*45)}px,${Math.sin(angle)*(100+ring*25)}px,${Math.sin(angle*2)*110}px)`;node.textContent=`${p.port}/${p.protocol}\n${p.service.name||'unknown'} · ${p.state}`;world.append(node);const row=document.createElement('div');row.className='result-row';row.textContent=`${p.port}/${p.protocol} · ${p.state} · ${p.service.name||'unknown'} ${p.service.product||''} ${p.service.version||''}`;$('results').append(row);});orient();}
let active=false,lastSignature='';
async function poll(){try{const data=await api('scan');const signature=JSON.stringify(data);if(signature!==lastSignature){lastSignature=signature;active=data.status==='running';$('scan').disabled=active;$('cancel-scan').disabled=!active;if(data.status==='running')scanStatus('Nmap 점검 중… 최대 150초\n'+data.command+(data.notice?'\n'+data.notice:''));else if(data.status==='done'){draw(data.hosts,data.target);const ports=data.hosts.flatMap(h=>h.ports);scanStatus(data.hosts.some(h=>h.timed_out)?'대상 응답 시간 초과. 결과가 불완전합니다.':`점검 완료 · 열린 포트 ${ports.filter(p=>p.state==='open').length}개. 포트가 열려 있다는 사실만으로 취약점이 확인된 것은 아닙니다.`);}else if(data.status==='error')scanStatus(data.error);else if(data.status==='cancelled')scanStatus('점검을 중단했어요.');}}catch(e){scanStatus('앱 연결을 확인해 주세요. '+e.message);}setTimeout(poll,1500);}
$('scan').onclick=async()=>{try{$('scan').disabled=true;await api('scan',{target:$('target').value.trim(),terminal:$('terminal').checked});lastSignature='';}catch(e){scanStatus(e.message);$('scan').disabled=false;}};
$('cancel-scan').onclick=async()=>{try{await api('scan/cancel',{});}catch(e){scanStatus(e.message);}};
const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;
$('dictate').onclick=()=>{if(!Speech){scanStatus('이 브라우저는 음성 입력을 지원하지 않아요. IP를 직접 입력해 주세요.');return;}const recognition=new Speech();recognition.lang='ko-KR';recognition.onresult=e=>{let text=e.results[0][0].transcript.trim().replace(/점|닷/g,'.').replace(/\s/g,'');$('target').value=text;scanStatus('인식된 IP를 확인하고 점검 시작을 눌러 주세요.');};recognition.onerror=e=>scanStatus('음성 입력 실패: '+e.error);try{recognition.start();}catch(e){scanStatus(e.message);}};
$('quit').onclick=async()=>{try{await api('quit',{});document.body.textContent='JARVIS를 종료했어요. 이 창을 닫아도 됩니다.';}catch(e){scanStatus(e.message);}};
draw([],null);poll();

let phoneOffset={pitch:0,roll:0}, phoneLatest=null, phoneWasConnected=false, pairingText='';
$('phone-enable').onclick=async()=>{try{const d=await api('phone/enable',{});pairingText=`맥 IP: ${d.addresses.join(' 또는 ')||'시스템 설정 → Wi-Fi → 세부사항에서 확인'} · 코드: ${d.pin} (5분 유효)`;$('phone-status').textContent=pairingText;}catch(e){$('phone-status').textContent=e.message;}};
$('phone-disable').onclick=async()=>{try{await api('phone/disable',{});pairingText='';$('phone-status').textContent='연결 해제됨';}catch(e){$('phone-status').textContent=e.message;}};
$('phone-center').onclick=()=>{if(phoneLatest)phoneOffset={pitch:phoneLatest.pitch,roll:phoneLatest.roll};};
async function phonePoll(){try{const d=await api('phone');if(d.connected){phoneLatest=d;const wrap=n=>((n+180)%360+360)%360-180;window.jarvisOrientation({pitch:wrap(d.pitch-phoneOffset.pitch),roll:wrap(d.roll-phoneOffset.roll)});$('phone-status').textContent='휴대폰 연결됨 · 기울여 화면을 회전하세요.';}else if(phoneWasConnected){$('phone-status').textContent=d.enabled?'휴대폰 신호 대기 중 · 휴대폰 앱을 화면에 띄워 주세요.':'연결 해제됨';}phoneWasConnected=d.connected;}catch(e){}setTimeout(phonePoll,100);}phonePoll();
